const ADD_MOVIE = "ADD_MOVIE";
const EDIT_MOVIE = "EDIT_MOVIE";
const REMOVE_MOVIE = "REMOVE_MOVIE";
const DELETE_MOVIE = "DELETE_MOVIE";
const SEARCH_MOVIE = "SEARCH_MOVIE";
const SEARCH_Rating = "SEARCH_Rating";
const FETCH_MOVIE = "FETCH_MOVIE";
export {
  ADD_MOVIE,
  EDIT_MOVIE,
  REMOVE_MOVIE,
  DELETE_MOVIE,
  SEARCH_MOVIE,
  SEARCH_Rating,
  FETCH_MOVIE
};
